export default {
    // Type_Customer
    GET_SUPPLIER_LOADING: 'GET_SUPPLIER_LOADING',
    GET_SUPPLIER_SUCCESS: 'GET_SUPPLIER_SUCCESS',
    GET_SUPPLIER_FAILURE: 'GET_SUPPLIER_FAILURE',
    ADD_SUPPLIER_LOADING: 'ADD_SUPPLIER_LOADING',
    ADD_SUPPLIER_SUCCESS: 'ADD_SUPPLIER_SUCCESS',
    ADD_SUPPLIER_FAILURE: 'ADD_SUPPLIER_FAILURE',

    // Type_Customer
    GET_CUSTOMER_LOADING: 'GET_CUSTOMER_LOADING',
    GET_CUSTOMER_SUCCESS: 'GET_CUSTOMER_SUCCESS',
    GET_CUSTOMER_FAILURE: 'GET_CUSTOMER_FAILURE',
    ADD_CUSTOMER_LOADING: 'ADD_CUSTOMER_LOADING',
    ADD_CUSTOMER_SUCCESS: 'ADD_CUSTOMER_SUCCESS',
    ADD_CUSTOMER_FAILURE: 'ADD_CUSTOMER_FAILURE',

     // Type_ImportTiketDetail
     GET_ORDERDETAIL_LOADING: 'GET_ORDERDETAIL_LOADING',
     GET_ORDERDETAIL_SUCCESS: 'GET_ORDERDETAIL_SUCCESS',
     GET_ORDERDETAIL_FAILURE: 'GET_ORDERDETAIL_FAILURE',
     ADD_ORDERDETAIL_LOADING: 'ADD_ORDERDETAIL_LOADING',
     ADD_ORDERDETAIL_SUCCESS: 'ADD_ORDERDETAIL_SUCCESS',
     ADD_ORDERDETAIL_FAILURE: 'ADD_ORDERDETAIL_FAILURE',

    // Type_ImportTiketDetail
    GET_IMPORTTIKET_LOADING: 'GET_IMPORTTIKET_LOADING',
    GET_IMPORTTIKET_SUCCESS: 'GET_IMPORTTIKET_SUCCESS',
    GET_IMPORTTIKET_FAILURE: 'GET_IMPORTTIKET_FAILURE',
    ADD_IMPORTTIKET_LOADING: 'ADD_IMPORTTIKET_LOADING',
    ADD_IMPORTTIKET_SUCCESS: 'ADD_IMPORTTIKET_SUCCESS',
    ADD_IMPORTTIKET_FAILURE: 'ADD_IMPORTTIKET_FAILURE',

    // Type_Product 
    GET_CATOGORIES_BYID_LOADING: 'GET_CATOGORIES_BYID_LOADING',
    GET_CATOGORIES_BYID_SUCCESS: 'GET_CATOGORIES_BYID_SUCCESS',
    GET_CATOGORIES_BYID_FAILURE: 'GET_CATOGORIES_BYID_FAILURE',
    GET_CATOGORIES_LOADING: 'GET_CATOGORIES_LOADING',
    GET_CATOGORIES_SUCCESS: 'GET_CATOGORIES_SUCCESS',
    GET_CATOGORIES_FAILURE: 'GET_CATOGORIES_FAILURE',
    ADD_CATOGORIES_LOADING: 'ADD_CATOGORIES_LOADING',
    ADD_CATOGORIES_SUCCESS: 'ADD_CATOGORIES_SUCCESS',
    ADD_CATOGORIES_FAILURE: 'ADD_CATOGORIES_FAILURE',
    UPDATE_CATOGORIES_LOADING: 'UPDATE_CATOGORIES_LOADING',
    UPDATE_CATOGORIES_SUCCESS: 'UPDATE_CATOGORIES_SUCCESS',
    UPDATE_CATOGORIES_FAILURE: 'UPDATE_CATOGORIES_FAILURE',
    DELETE_CATOGORIES_LOADING: 'DELETE_CATOGORIES_LOADING',
    DELETE_CATOGORIES_SUCCESS: 'DELETE_CATOGORIES_SUCCESS',
    DELETE_CATOGORIES_FAILURE: 'DELETE_CATOGORIES_FAILURE',
    // Type_Product
    GET_PRODUCT_OF_SHOP_LOADING: 'GET_PRODUCT_OF_SHOP_LOADING',
    GET_PRODUCT_OF_SHOP_SUCCESS: 'GET_PRODUCT_OF_SHOP_SUCCESS',
    GET_PRODUCT_OF_SHOP_FAILURE: 'GET_PRODUCT_OF_SHOP_FAILURE',
    ADD_PRODUCT_LOADING: 'ADD_PRODUCT_LOADING',
    ADD_PRODUCT_SUCCESS: 'ADD_PRODUCT_SUCCESS',
    ADD_PRODUCT_FAILURE: 'ADD_PRODUCT_FAILURE',
    UPDATE_PRODUCT_LOADING: 'UPDATE_PRODUCT_LOADING',
    UPDATE_PRODUCT_SUCCESS: 'UPDATE_PRODUCT_SUCCESS',
    UPDATE_PRODUCT_FAILURE: 'UPDATE_PRODUCT_FAILURE',
    DELETE_PRODUCT_LOADING: 'DELETE_PRODUCT_LOADING',
    DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
    DELETE_PRODUCT_FAILURE: 'DELETE_PRODUCT_FAILURE',
    // Type info shop
    SHOP_INFO_LOADING: 'SHOP_INFO_LOADING',
    SHOP_INFO_SUCCESS: 'SHOP_INFO_SUCCESS',
    SHOP_INFO_FAILURE: 'SHOP_INFO_FAILURE',
    SHOP_INFO_INSERT_SUCCESS: 'SHOP_INFO_INSERT_SUCCESS',
    SHOP_INFO_INSERT_FAILURE: 'SHOP_INFO_INSERT_FAILURE',
    SHOP_INFO_BY_USER_ID_LOADING: 'SHOP_INFO_BY_USER_ID_LOADING',
    SHOP_INFO_BY_USER_ID_FAILURE: 'SHOP_INFO_BY_USER_ID_FAILURE',
    SHOP_INFO_BY_USER_ID_SUCCESS: 'SHOP_INFO_BY_USER_ID_SUCCESS',

    // Type_Account
    AUTH_ACCOUNT_LOADING: 'AUTH_ACCOUNT_LOADING',
    AUTH_ACCOUNT_SUCCESS: 'AUTH_ACCOUNT_SUCCESS',
    AUTH_ACCOUNT_FAILURE: 'AUTH_ACCOUNT_FAILURE',
    AUTH_CHANGEPASSWORD_SUCCESS: 'AUTH_CHANGEPASSWORD_SUCCESS',
    AUTH_CHANGEPASSWORD_FAILURE: 'AUTH_CHANGEPASSWORD_FAILURE',

    // Type Authen
    AUTH_REGISTER_FAILURE: 'AUTH_REGISTER_FAILURE',
    AUTH_REGISTER_SUCCESS: 'AUTH_REGISTER_SUCCES',

    LOG_IN_FAILURE: 'LOG_IN_FAILURE',
    LOGGING_IN: 'LOGGING_IN',
    LOG_IN_SUCCESS: 'LOG_IN_SUCCESS',
    LOG_OUT: 'LOG_OUT',

}
